server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
      - id: api
        uri: http://localhost:8000
        predicates:
          - Path=/api/**

logging:
  level:
    org.springframework: INFO
    com.buoygateway: INFO
